// Catálogo completo de monedas ISO 4217 para el selector de Configuración — generado con
// Intl.supportedValuesOf('currency') + Intl.DisplayNames en español, para no dejar afuera
// monedas menos comunes globalmente (como el colón costarricense, CRC) por armar la lista a
// mano. Etiquetas ordenadas alfabéticamente en español para que sean fáciles de ubicar en
// un selector sin buscador.

export const currencyOptions: { value: string; label: string }[] = [
  { value: "AFN", label: "afgani afgano (AFN)" },
  { value: "MGA", label: "ariari malgache (MGA)" },
  { value: "PAB", label: "balboa panameño (PAB)" },
  { value: "THB", label: "bat tailandés (THB)" },
  { value: "ETB", label: "bir etíope (ETB)" },
  { value: "VES", label: "bolívar venezolano (VES)" },
  { value: "BOB", label: "boliviano (BOB)" },
  { value: "GHS", label: "cedi ghanés (GHS)" },
  { value: "KES", label: "chelín keniano (KES)" },
  { value: "SOS", label: "chelín somalí (SOS)" },
  { value: "TZS", label: "chelín tanzano (TZS)" },
  { value: "UGX", label: "chelín ugandés (UGX)" },
  { value: "CRC", label: "colón costarricense (CRC)" },
  { value: "SVC", label: "colón salvadoreño (SVC)" },
  { value: "NIO", label: "córdoba oro (NIO)" },
  { value: "CZK", label: "corona checa (CZK)" },
  { value: "DKK", label: "corona danesa (DKK)" },
  { value: "ISK", label: "corona islandesa (ISK)" },
  { value: "NOK", label: "corona noruega (NOK)" },
  { value: "SEK", label: "corona sueca (SEK)" },
  { value: "GMD", label: "dalasi gambiano (GMD)" },
  { value: "XDR", label: "derechos especiales de giro (XDR)" },
  { value: "DZD", label: "dinar argelino (DZD)" },
  { value: "BHD", label: "dinar bareiní (BHD)" },
  { value: "IQD", label: "dinar iraquí (IQD)" },
  { value: "JOD", label: "dinar jordano (JOD)" },
  { value: "KWD", label: "dinar kuwaití (KWD)" },
  { value: "LYD", label: "dinar libio (LYD)" },
  { value: "MKD", label: "dinar macedonio (MKD)" },
  { value: "RSD", label: "dinar serbio (RSD)" },
  { value: "TND", label: "dinar tunecino (TND)" },
  { value: "AED", label: "dírham de los Emiratos Árabes Unidos (AED)" },
  { value: "MAD", label: "dírham marroquí (MAD)" },
  { value: "STN", label: "dobra santotomense (STN)" },
  { value: "AUD", label: "dólar australiano (AUD)" },
  { value: "BSD", label: "dólar bahameño (BSD)" },
  { value: "BBD", label: "dólar barbadense (BBD)" },
  { value: "BZD", label: "dólar beliceño (BZD)" },
  { value: "BMD", label: "dólar bermudeño (BMD)" },
  { value: "BND", label: "dólar bruneano (BND)" },
  { value: "CAD", label: "dólar canadiense (CAD)" },
  { value: "KYD", label: "dólar de las Islas Caimán (KYD)" },
  { value: "TTD", label: "dólar de Trinidad y Tobago (TTD)" },
  { value: "XCD", label: "dólar del Caribe Oriental (XCD)" },
  { value: "USD", label: "dólar estadounidense (USD)" },
  { value: "FJD", label: "dólar fiyiano (FJD)" },
  { value: "GYD", label: "dólar guyanés (GYD)" },
  { value: "HKD", label: "dólar hongkonés (HKD)" },
  { value: "JMD", label: "dólar jamaicano (JMD)" },
  { value: "LRD", label: "dólar liberiano (LRD)" },
  { value: "NAD", label: "dólar namibio (NAD)" },
  { value: "NZD", label: "dólar neozelandés (NZD)" },
  { value: "SBD", label: "dólar salomonense (SBD)" },
  { value: "SGD", label: "dólar singapurense (SGD)" },
  { value: "SRD", label: "dólar surinamés (SRD)" },
  { value: "ZWL", label: "dólar zimbabuense (ZWL)" },
  { value: "VND", label: "dong vietnamita (VND)" },
  { value: "AMD", label: "dram armenio (AMD)" },
  { value: "CVE", label: "escudo de Cabo Verde (CVE)" },
  { value: "PLN", label: "esloti polaco (PLN)" },
  { value: "EUR", label: "euro (EUR)" },
  { value: "ANG", label: "florín antillano (ANG)" },
  { value: "AWG", label: "florín arubeño (AWG)" },
  { value: "XCG", label: "florín caribeño (XCG)" },
  { value: "HUF", label: "forinto húngaro (HUF)" },
  { value: "BIF", label: "franco burundés (BIF)" },
  { value: "XAF", label: "franco CFA de África Central (XAF)" },
  { value: "XOF", label: "franco CFA de África Occidental (XOF)" },
  { value: "XPF", label: "franco CFP (XPF)" },
  { value: "KMF", label: "franco comorense (KMF)" },
  { value: "CDF", label: "franco congoleño (CDF)" },
  { value: "GNF", label: "franco guineano (GNF)" },
  { value: "RWF", label: "franco ruandés (RWF)" },
  { value: "CHF", label: "franco suizo (CHF)" },
  { value: "DJF", label: "franco yibutiano (DJF)" },
  { value: "UAH", label: "grivna ucraniana (UAH)" },
  { value: "PYG", label: "guaraní paraguayo (PYG)" },
  { value: "BTN", label: "gultrum butanés (BTN)" },
  { value: "HTG", label: "gurde haitiano (HTG)" },
  { value: "MMK", label: "kiat de Myanmar (MMK)" },
  { value: "PGK", label: "kina papú (PGK)" },
  { value: "LAK", label: "kip laosiano (LAK)" },
  { value: "MWK", label: "kuacha malauí (MWK)" },
  { value: "ZMW", label: "kuacha zambiano (ZMW)" },
  { value: "AOA", label: "kuanza angoleño (AOA)" },
  { value: "HRK", label: "kuna croata (HRK)" },
  { value: "GEL", label: "lari georgiano (GEL)" },
  { value: "ALL", label: "lek albanés (ALL)" },
  { value: "HNL", label: "lempira hondureño (HNL)" },
  { value: "SLL", label: "leona sierraleonesa (1964–2022) (SLL)" },
  { value: "SLE", label: "leona sierraleonesa (SLE)" },
  { value: "MDL", label: "leu moldavo (MDL)" },
  { value: "RON", label: "leu rumano (RON)" },
  { value: "BGN", label: "leva búlgara (BGN)" },
  { value: "SHP", label: "libra de Santa Elena (SHP)" },
  { value: "EGP", label: "libra egipcia (EGP)" },
  { value: "GBP", label: "libra esterlina (GBP)" },
  { value: "GIP", label: "libra gibraltareña (GIP)" },
  { value: "LBP", label: "libra libanesa (LBP)" },
  { value: "FKP", label: "libra malvinense (FKP)" },
  { value: "SYP", label: "libra siria (SYP)" },
  { value: "SDG", label: "libra sudanesa (SDG)" },
  { value: "SSP", label: "libra sursudanesa (SSP)" },
  { value: "SZL", label: "lilangeni esuatiní (SZL)" },
  { value: "TRY", label: "lira turca (TRY)" },
  { value: "LSL", label: "loti lesotense (LSL)" },
  { value: "AZN", label: "manat azerbaiyano (AZN)" },
  { value: "TMT", label: "manat turcomano (TMT)" },
  { value: "BAM", label: "marco convertible de Bosnia y Herzegovina (BAM)" },
  { value: "MZN", label: "metical mozambiqueño (MZN)" },
  { value: "NGN", label: "naira nigeriano (NGN)" },
  { value: "ERN", label: "nakfa eritreo (ERN)" },
  { value: "TWD", label: "nuevo dólar taiwanés (TWD)" },
  { value: "ILS", label: "nuevo séquel israelí (ILS)" },
  { value: "ZWG", label: "oro zimbabuense (ZWG)" },
  { value: "TOP", label: "paanga tongano (TOP)" },
  { value: "MOP", label: "pataca macaense (MOP)" },
  { value: "ARS", label: "peso argentino (ARS)" },
  { value: "CLP", label: "peso chileno (CLP)" },
  { value: "COP", label: "peso colombiano (COP)" },
  { value: "CUP", label: "peso cubano (CUP)" },
  { value: "CUC", label: "peso cubano convertible (CUC)" },
  { value: "DOP", label: "peso dominicano (DOP)" },
  { value: "PHP", label: "peso filipino (PHP)" },
  { value: "MXN", label: "peso mexicano (MXN)" },
  { value: "UYU", label: "peso uruguayo (UYU)" },
  { value: "BWP", label: "pula botsuano (BWP)" },
  { value: "GTQ", label: "quetzal guatemalteco (GTQ)" },
  { value: "ZAR", label: "rand sudafricano (ZAR)" },
  { value: "BRL", label: "real brasileño (BRL)" },
  { value: "QAR", label: "rial catarí (QAR)" },
  { value: "IRR", label: "rial iraní (IRR)" },
  { value: "OMR", label: "rial omaní (OMR)" },
  { value: "SAR", label: "rial saudí (SAR)" },
  { value: "YER", label: "rial yemení (YER)" },
  { value: "KHR", label: "riel camboyano (KHR)" },
  { value: "MYR", label: "ringit malasio (MYR)" },
  { value: "BYN", label: "rublo bielorruso (BYN)" },
  { value: "RUB", label: "rublo ruso (RUB)" },
  { value: "MVR", label: "rufiya maldiva (MVR)" },
  { value: "LKR", label: "rupia esrilanquesa (LKR)" },
  { value: "INR", label: "rupia india (INR)" },
  { value: "IDR", label: "rupia indonesia (IDR)" },
  { value: "MUR", label: "rupia mauriciana (MUR)" },
  { value: "NPR", label: "rupia nepalí (NPR)" },
  { value: "PKR", label: "rupia pakistaní (PKR)" },
  { value: "SCR", label: "rupia seychellense (SCR)" },
  { value: "PEN", label: "sol peruano (PEN)" },
  { value: "KGS", label: "som kirguís (KGS)" },
  { value: "TJS", label: "somoni tayiko (TJS)" },
  { value: "UZS", label: "sum uzbeko (UZS)" },
  { value: "BDT", label: "taka bangladesí (BDT)" },
  { value: "WST", label: "tala samoano (WST)" },
  { value: "KZT", label: "tengue kazajo (KZT)" },
  { value: "MNT", label: "tugrik mongol (MNT)" },
  { value: "MRU", label: "uguiya mauritano (MRU)" },
  { value: "VUV", label: "vatu vanuatense (VUV)" },
  { value: "KPW", label: "won norcoreano (KPW)" },
  { value: "KRW", label: "won surcoreano (KRW)" },
  { value: "XSU", label: "XSU (XSU)" },
  { value: "JPY", label: "yen japonés (JPY)" },
  { value: "CNY", label: "yuan renminbi (CNY)" },
]

// Moneda por defecto mientras la usuaria no elige una en Configuración — dólar
// estadounidense, la más neutral internacionalmente. No se fuerza a elegir una moneda en el
// primer login: profiles.currency queda null hasta que se seleccione una.
export const DEFAULT_CURRENCY = 'USD'

/**
 * Formatea un monto de dinero según la moneda de la cuenta. Sin tabla de símbolos a mano —
 * Intl.NumberFormat ya sabe si va $1,234.00 o CRC 1 234,00 según la moneda.
 */
export function formatCurrency(amount: number, currency: string | null | undefined): string {
  return new Intl.NumberFormat('es', {
    style: 'currency',
    currency: currency || DEFAULT_CURRENCY,
    maximumFractionDigits: 2,
  }).format(amount)
}
